sudo: required
dist: trusty

group: edge

notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true

language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9

    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - libiomp-dev
      env:
       - COMPILER=clang++
# libiomp is a very strange abberation in trusty
# changed to libomp in newer Ubuntu versions.
       - CXXFLAGS="-fopenmp=libiomp5"
    - os: osx
      compiler: gcc
      env: COMPILER=g++


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get update;
    sudo apt-get install pkg-config autoconf-archive libicu-dev libxml2-dev libbz2-dev zlib1g-dev libtar-dev libboost-dev libboost-regex-dev;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update;
    brew install pkg-config;
    brew install autoconf-archive;
    brew install icu4c;
    brew install libxml2;
    brew install bzip2;
    brew install zlib;
    brew install gnu-tar;
    brew outdated boost || brew upgrade boost;
    fi

install:
  - bash bootstrap.sh
  - ./configure
  - make CXX=$COMPILER
  - sudo make CXX=$COMPILER install
script:
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make CXX=$COMPILER check
after_failure:
  - cat src/test-suite.log
  - cat config.log
