sudo: required
dist: trusty

matrix:
  include:
    - compiler gcc
      addons:
        apt:
	  sources:
	    - ubuntu-tool-chain-r-test
	  packages:
	    - g++-4.9
      env: COMPILER=g++4.9
   - compiler: clang
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
           - llvm-toolchain-precise-3.7
         packages:
           - clang-3.7
      env: COMPILER=clang++-3.7

language: cpp
before_install:
  - sudo apt-get update
  - sudo apt-get install pkg-config autoconf-archive libicu-dev libxml2-dev libbz2-dev zlib1g-dev libtar-dev
install:
  - bash bootstrap.sh
  - ./configure
  - make
  - sudo make install
script:
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make check
after_failure:
  - cat src/test-suite.log
  - cat config.log
