sudo: required
dist: trusty

group: edge

notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true

language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9

    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - libiomp-dev
      env:
       - COMPILER=clang++
# libiomp is a very strange abberation in trusty
# changed to libomp in newer Ubuntu versions.
       - CXXFLAGS="-fopenmp=libiomp5"
    - os: osx
      compiler: gcc
      env: COMPILER=g++


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; else brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install pkg-config; else brew install pkg-config; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install autoconf-archive; else brew install autoconf-archive; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libicu-dev; else brew install libicu-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libxml2-dev; else brew install libxml2-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libbz2-dev; else brew install libbz2-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install zlib1g-dev; else brew install zlib1g-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libtar-dev; else brew install libtar-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-dev; else brew install libboost-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-regex-dev; else brew install libboost-regex-dev; fi

install:
  - bash bootstrap.sh
  - ./configure
  - make CXX=$COMPILER
  - sudo make CXX=$COMPILER install
script:
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make CXX=$COMPILER check
after_failure:
  - cat src/test-suite.log
  - cat config.log
