.TH ticcutils 1 "2012 August 8"

.SH NAME
ticcutils - A bunch of useful C++ goodies

.SH DESCRIPTION
Ticc Utils is a collection of generic C++ software which is used in a lot of
programs produced at Ticc.

All components are described in separate man pages.

.SH see
.B ticc_unit_test
.B ticc_logstream
.B ticc_string
.B ticc_prettyprint

.SH AUTHORS
Ko van der Sloot Timbl@uvt.nl


